export const courses = [
  {
    id: 1,
      slug: "devops-cloud-engineering",  // ← ye add karo
    title: "DevOps & Cloud Engineering",
    subtitle: "With Live Project Deployment on AWS & Azure",
    tag: "Docker, K8s, AWS",
    emoji: "☁️",
    rating: 4.8,
    learners: "1.2K",
    mentor: "Omprakash Paliwal",
    mentorRole: "SRE CloudOps Engineer",
    mentorImage: "/omparkash.png",
    duration: "5 Months",
    time: "Mon / Thu, 4:00 PM – 6:00 PM",
    batch: "15 Students",
    format: "Live, Online, Interactive",
    imgSrc: "/cloud.png",
    partners: ["Microsoft Azure", "AWS", "Docker"],
    highlights: [
      "Hands-on with Docker, Kubernetes, Jenkins & Ansible",
      "Live project deployment on AWS & Azure",
      "Industry-recognized DevOpsFarm Certificate",
      "Mentorship from SRE Engineers with 8+ yrs experience",
      "Real-world CI/CD pipeline building",
      "Job assistance & career support",
    ],
    topics: [
      { week: "Week 1–2", title: "Linux & Git Basics", desc: "Shell scripting, Git workflows, version control best practices" },
      { week: "Week 3–4", title: "Docker & Containerization", desc: "Docker images, containers, Dockerfile, Docker Compose" },
      { week: "Week 5–7", title: "Kubernetes (K8s)", desc: "Pods, deployments, services, ingress, Helm charts" },
      { week: "Week 8–10", title: "Jenkins CI/CD", desc: "Pipeline as code, Jenkinsfile, automated testing & deployment" },
      { week: "Week 11–13", title: "AWS & Azure Basics", desc: "EC2, S3, IAM, VPC, Azure DevOps, cloud-native services" },
      { week: "Week 14–16", title: "Ansible & Terraform", desc: "Infrastructure as code, configuration management, IaC best practices" },
      { week: "Week 17–18", title: "Monitoring & Logging", desc: "Prometheus, Grafana, ELK stack, alerting strategies" },
      { week: "Week 19–20", title: "Live Project Deployment", desc: "End-to-end deployment of a real-world application on cloud" },
    ],
    social: { linkedin: "#", twitter: "#", instagram: "#" },
  },
];